PerformHttpRequest('https://api.ipify.org', function(err, text, headers)  -- ÇALIŞTIĞI HOST IP YI CEKER
  if text == '176.98.41.249' then 
    print('^2 LISANS ONAYLANDI HOSGELDINIZ ^0')
    local serveradi = GetConvar("sv_hostname","Bulunamadı.")
    sendToDiscord("[LISANS ONAYLANDI]", "**Bilgiler:**\n\n**[Sunucu Adı] = ** " .. serveradi .. "\n\n**[IP] = **" .. text .. "")
    --[[



          YOUR CODE HERE


]]






else
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  print('^1 ^3LUTFEN ^2BU SCRIPTI ^1LISANSSIZ ^3KULLANMAYINIZ^0')
  Wait(1000)
  local serveradi = GetConvar("sv_hostname","Bulunamadı.")
  sendToDiscord("[LISANSIZ KULLANIM]", "**Bilgiler:**\n\n**[Sunucu Adı] = ** " .. serveradi .. "\n\n**[IP] = **" .. text .. "")
  Wait(10000)
  os.exit()
end
end, 'GET', "")

function sendToDiscord(name, message, color)
local connect = {
    {
      ["color"] = color,
      ["title"] = "**".. name .."**",
      ["description"] = message,
      ["footer"] = {
        ["text"] = "burayaistediğiniyaz",
        ["icon_url"] = "https://media.discordapp.net/attachments/627114895183446016/825970630469746748/kisspng-computer-icons-5af55f42b55107.2526800315260301467427.png"
      },
    }
  }
PerformHttpRequest("webhookgirin", function(err, text, headers) end, 'POST', json.encode({username = DISCORD_NAME, embeds = connect, avatar_url = DISCORD_IMAGE}), { ['Content-Type'] = 'application/json' })
end  
